AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  python3.10

  Sample SAM Template for lastnightscores

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 900
    MemorySize: 10240
Resources:
  DailyGenerateFunction:
    Type: AWS::Serverless::Function
    Properties:
      PackageType: Image
      ImageConfig:
        Command:
          - daily_generate_function.lambda_handler
      Architectures:
        - x86_64
      Environment:
        Variables:
          API_KEY: ${API_KEY}
          BUCKET_NAME: ${BUCKET_NAME}
          SENDER_EMAIL: ${SENDER_EMAIL}
          SENDER_PASSWORD: ${SENDER_PASSWORD}
          RECEIVE_EMAIL: ${RECEIVE_EMAIL}
          SITENAME: ${SITENAME}
          GITHUB_USERNAME: ${GITHUB_USERNAME}
          GITHUB_TOKEN: ${GITHUB_TOKEN}
          IS_SERVER: ${IS_SERVER}
          BINARY_LOCATION: ${BINARY_LOCATION}
      Events:
        DailyGenerateApi:
          Type: Api
          Properties:
            Path: /lastnightscores-daily-generate
            Method: get
    Metadata:
      Dockerfile: Dockerfile
      DockerContext: ./src
      DockerTag: python3.10-v1

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  DailyGenerateFunction:
    Description: "Hello World Lambda Function ARN"
    Value: !GetAtt DailyGenerateFunction.Arn
  DailyGenerateFunctionIamRole:
    Description: "Implicit IAM Role created for Hello World function"
    Value: !GetAtt DailyGenerateFunctionRole.Arn
  DailyGenerateApi:
    Description: "Implicit IAM Role created for Daily Generate function"
    Value: !GetAtt DailyGenerateFunctionRole.Arn


